Added grunt-cli and removed optipng

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -17,27 +17,12 @@ if [ `gem list compass -i` == 'false' ]; then
 	gem install compass
 fi
 
-if [ ! -x $OPENSHIFT_DATA_DIR/bin/optipng ]; then
-	# Install optipng it's in our git repo
-	cd $OPENSHIFT_TMP_DIR
-	tar -xzf $OPENSHIFT_REPO_DIR/binary/optipng-0.7.4.tgz
-	cd "$OPENSHIFT_TMP_DIR"optipng-0.7.4
-	echo "Configuring optipng"
-	./configure \
-	      --prefix=$OPENSHIFT_DATA_DIR
-	echo "Configured optipng"
-	make -j
-	echo "Build optipng"
-	make install
-	echo "Installed optipng"
-fi
-
 #put all the things on the PATH
 export PATH=$OPENSHIFT_DATA_DIR/bin:$OPENSHIFT_DATA_DIR/gems/bin:$PATH
 export GEM_HOME=$OPENSHIFT_DATA_DIR/gems
 
 if [ -f "${OPENSHIFT_REPO_DIR}"/Gruntfile.js ]; then
-    (cd "${OPENSHIFT_REPO_DIR}"; node_modules/grunt-cli/bin/grunt build || { echo 'Client build failed' ; exit 1; })
+    (cd "${OPENSHIFT_REPO_DIR}"; node node_modules/grunt-cli/bin/grunt build || { echo 'Client build failed' ; exit 1; })
 fi
 
 exit 0;
